services:
  api:
    container_name: sf-api
    build: ./backend/
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python src/app.py'
    volumes:
      - ./backend/src:/app/src
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env

  frontend:
    container_name: sf-frontend
    build:
      context: ./frontend/
      target: development
    depends_on:
      - db
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: sh -c "yarn install && yarn dev"
    env_file:
      - .env
                  
  db:
    container_name: sf-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    restart: always
